# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestResultViewer.ui'
#
# Created: Sat Apr 02 16:30:21 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(738, 638)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.TotalTests = QtGui.QLabel(self.groupBox)
        self.TotalTests.setObjectName(_fromUtf8("TotalTests"))
        self.gridLayout.addWidget(self.TotalTests, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.PercentFailed = QtGui.QLabel(self.groupBox)
        self.PercentFailed.setObjectName(_fromUtf8("PercentFailed"))
        self.gridLayout.addWidget(self.PercentFailed, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 2, 2)
        self.TestResultList = QtGui.QTreeWidget(self.frame)
        self.TestResultList.setObjectName(_fromUtf8("TestResultList"))
        self.gridLayout_3.addWidget(self.TestResultList, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.ExitCode = QtGui.QLabel(self.groupBox_2)
        self.ExitCode.setObjectName(_fromUtf8("ExitCode"))
        self.gridLayout_4.addWidget(self.ExitCode, 1, 0, 1, 1)
        self.ReferenceExitCode = QtGui.QLabel(self.groupBox_2)
        self.ReferenceExitCode.setObjectName(_fromUtf8("ReferenceExitCode"))
        self.gridLayout_4.addWidget(self.ReferenceExitCode, 2, 0, 1, 1)
        self.Command = QtGui.QLabel(self.groupBox_2)
        self.Command.setObjectName(_fromUtf8("Command"))
        self.gridLayout_4.addWidget(self.Command, 0, 0, 1, 1)
        self.Stdout = QtGui.QTextBrowser(self.groupBox_2)
        self.Stdout.setObjectName(_fromUtf8("Stdout"))
        self.gridLayout_4.addWidget(self.Stdout, 4, 0, 1, 1)
        self.Stderr = QtGui.QTextBrowser(self.groupBox_2)
        self.Stderr.setObjectName(_fromUtf8("Stderr"))
        self.gridLayout_4.addWidget(self.Stderr, 6, 0, 1, 1)
        self.ReferenceStdoutStderr = QtGui.QTextBrowser(self.groupBox_2)
        self.ReferenceStdoutStderr.setObjectName(_fromUtf8("ReferenceStdoutStderr"))
        self.gridLayout_4.addWidget(self.ReferenceStdoutStderr, 8, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 7, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 738, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuOpen = QtGui.QMenu(self.menubar)
        self.menuOpen.setObjectName(_fromUtf8("menuOpen"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.menuOpen.addAction(self.actionOpen)
        self.menubar.addAction(self.menuOpen.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Test Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.TotalTests.setText(QtGui.QApplication.translate("MainWindow", "Total Tests:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.PercentFailed.setText(QtGui.QApplication.translate("MainWindow", "% Failed:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.TestResultList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.TestResultList.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Elapsed Time", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Test Output", None, QtGui.QApplication.UnicodeUTF8))
        self.ExitCode.setText(QtGui.QApplication.translate("MainWindow", "Exit: ", None, QtGui.QApplication.UnicodeUTF8))
        self.ReferenceExitCode.setText(QtGui.QApplication.translate("MainWindow", "Reference Exit: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Command.setText(QtGui.QApplication.translate("MainWindow", "Command: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "stdout", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "stderr", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Reference stdout+stderr", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpen.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))

